// Code generated by hand — equivalent to protoc-gen-go output.
// Regenerate with: protoc --go_out=. --go_opt=paths=source_relative messages.proto

package network

import (
	"google.golang.org/protobuf/runtime/protoimpl"
)

// ── MsgType enum ─────────────────────────────────────────────────────────────

type MsgType int32

const (
	MsgType_UNKNOWN         MsgType = 0
	MsgType_JOIN_TABLE      MsgType = 1
	MsgType_PLAYER_READY    MsgType = 2
	MsgType_SHUFFLE_STEP    MsgType = 3
	MsgType_SHUFFLE_COMMIT  MsgType = 4
	MsgType_PARTIAL_DECRYPT MsgType = 5
	MsgType_PLAYER_ACTION   MsgType = 6
	MsgType_GAME_STATE_SYNC MsgType = 7
	MsgType_HEARTBEAT       MsgType = 8
	MsgType_TIMEOUT_VOTE    MsgType = 9
	MsgType_HAND_RESULT     MsgType = 10
	MsgType_LEAVE_TABLE     MsgType = 11
)

// ── Envelope ─────────────────────────────────────────────────────────────────

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=network.MsgType" json:"type,omitempty"`
	SenderId  string  `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Seq       int64   `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp int64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   []byte  `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature []byte  `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Envelope) Reset()         {}
func (x *Envelope) String() string { return x.SenderId }
func (x *Envelope) ProtoMessage()  {}
func (x *Envelope) GetType() MsgType   { return x.Type }
func (x *Envelope) GetSenderId() string { return x.SenderId }
func (x *Envelope) GetSeq() int64      { return x.Seq }
func (x *Envelope) GetTimestamp() int64 { return x.Timestamp }
func (x *Envelope) GetPayload() []byte  { return x.Payload }
func (x *Envelope) GetSignature() []byte { return x.Signature }

// ── JoinTable ─────────────────────────────────────────────────────────────────

type JoinTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId      string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	PlayerName   string `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	BuyIn        int64  `protobuf:"varint,3,opt,name=buy_in,json=buyIn,proto3" json:"buy_in,omitempty"`
	SraPubKeyE   []byte `protobuf:"bytes,4,opt,name=sra_pub_key_e,json=sraPubKeyE,proto3" json:"sra_pub_key_e,omitempty"`
	SessionNonce []byte `protobuf:"bytes,5,opt,name=session_nonce,json=sessionNonce,proto3" json:"session_nonce,omitempty"`
}

func (x *JoinTable) Reset()        {}
func (x *JoinTable) String() string { return x.PlayerName }
func (x *JoinTable) ProtoMessage() {}
func (x *JoinTable) GetTableId() string    { return x.TableId }
func (x *JoinTable) GetPlayerName() string { return x.PlayerName }
func (x *JoinTable) GetBuyIn() int64       { return x.BuyIn }
func (x *JoinTable) GetSraPubKeyE() []byte { return x.SraPubKeyE }
func (x *JoinTable) GetSessionNonce() []byte { return x.SessionNonce }

// ── PlayerReady ───────────────────────────────────────────────────────────────

type PlayerReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum int64  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
}

func (x *PlayerReady) Reset()        {}
func (x *PlayerReady) String() string { return x.TableId }
func (x *PlayerReady) ProtoMessage() {}
func (x *PlayerReady) GetTableId() string { return x.TableId }
func (x *PlayerReady) GetHandNum() int64  { return x.HandNum }

// ── ShuffleStep ───────────────────────────────────────────────────────────────

type ShuffleStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId         string   `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum         int64    `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId        string   `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Deck            [][]byte `protobuf:"bytes,4,rep,name=deck,proto3" json:"deck,omitempty"`
	CommitmentHash  []byte   `protobuf:"bytes,5,opt,name=commitment_hash,json=commitmentHash,proto3" json:"commitment_hash,omitempty"`
	CommitmentNonce []byte   `protobuf:"bytes,6,opt,name=commitment_nonce,json=commitmentNonce,proto3" json:"commitment_nonce,omitempty"`
}

func (x *ShuffleStep) Reset()        {}
func (x *ShuffleStep) String() string { return t.PlayerId }
func (x *ShuffleStep) ProtoMessage() {}
func (x *ShuffleStep) GetTableId() string        { return x.TableId }
func (x *ShuffleStep) GetHandNum() int64          { return x.HandNum }
func (x *ShuffleStep) GetPlayerId() string        { return x.PlayerId }
func (x *ShuffleStep) GetDeck() [][]byte          { return x.Deck }
func (x *ShuffleStep) GetCommitmentHash() []byte  { return x.CommitmentHash }
func (x *ShuffleStep) GetCommitmentNonce() []byte { return x.CommitmentNonce }

// ── ZKProofWire ───────────────────────────────────────────────────────────────

type ZKProofWire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A []byte `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B []byte `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	S []byte `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	H []byte `protobuf:"bytes,4,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *ZKProofWire) Reset()        {}
func (x *ZKProofWire) String() string { return "zkproof" }
func (x *ZKProofWire) ProtoMessage() {}
func (x *ZKProofWire) GetA() []byte { return x.A }
func (x *ZKProofWire) GetB() []byte { return x.B }
func (x *ZKProofWire) GetS() []byte { return x.S }
func (x *ZKProofWire) GetH() []byte { return x.H }

// ── PartialDecrypt ────────────────────────────────────────────────────────────

type PartialDecrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId    string       `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum    int64        `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId   string       `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CardIndex  int32        `protobuf:"varint,4,opt,name=card_index,json=cardIndex,proto3" json:"card_index,omitempty"`
	Ciphertext []byte       `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Result     []byte       `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Proof      *ZKProofWire `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *PartialDecrypt) Reset()        {}
func (x *PartialDecrypt) String() string { return x.PlayerId }
func (x *PartialDecrypt) ProtoMessage() {}
func (x *PartialDecrypt) GetTableId() string      { return x.TableId }
func (x *PartialDecrypt) GetHandNum() int64        { return x.HandNum }
func (x *PartialDecrypt) GetPlayerId() string      { return x.PlayerId }
func (x *PartialDecrypt) GetCardIndex() int32      { return x.CardIndex }
func (x *PartialDecrypt) GetCiphertext() []byte    { return x.Ciphertext }
func (x *PartialDecrypt) GetResult() []byte        { return x.Result }
func (x *PartialDecrypt) GetProof() *ZKProofWire   { return x.Proof }

// ── PlayerAction ──────────────────────────────────────────────────────────────

type PlayerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId  string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum  int64  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action   int32  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`
	Amount   int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Seq      int64  `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *PlayerAction) Reset()        {}
func (x *PlayerAction) String() string { return x.PlayerId }
func (x *PlayerAction) ProtoMessage() {}
func (x *PlayerAction) GetTableId() string  { return x.TableId }
func (x *PlayerAction) GetHandNum() int64   { return x.HandNum }
func (x *PlayerAction) GetPlayerId() string { return x.PlayerId }
func (x *PlayerAction) GetAction() int32    { return x.Action }
func (x *PlayerAction) GetAmount() int64    { return x.Amount }
func (x *PlayerAction) GetSeq() int64       { return x.Seq }

// ── GameStateSync ─────────────────────────────────────────────────────────────

type GameStateSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId      string   `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum      int64    `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	Phase        int32    `protobuf:"varint,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Pot          int64    `protobuf:"varint,4,opt,name=pot,proto3" json:"pot,omitempty"`
	CurrentBet   int64    `protobuf:"varint,5,opt,name=current_bet,json=currentBet,proto3" json:"current_bet,omitempty"`
	ActingPlayer string   `protobuf:"bytes,6,opt,name=acting_player,json=actingPlayer,proto3" json:"acting_player,omitempty"`
	StateRoot    []byte   `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ActionLog    [][]byte `protobuf:"bytes,8,rep,name=action_log,json=actionLog,proto3" json:"action_log,omitempty"`
}

func (x *GameStateSync) Reset()        {}
func (x *GameStateSync) String() string { return x.TableId }
func (x *GameStateSync) ProtoMessage() {}
func (x *GameStateSync) GetTableId() string      { return x.TableId }
func (x *GameStateSync) GetHandNum() int64        { return x.HandNum }
func (x *GameStateSync) GetPhase() int32          { return x.Phase }
func (x *GameStateSync) GetPot() int64            { return x.Pot }
func (x *GameStateSync) GetCurrentBet() int64     { return x.CurrentBet }
func (x *GameStateSync) GetActingPlayer() string  { return x.ActingPlayer }
func (x *GameStateSync) GetStateRoot() []byte     { return x.StateRoot }
func (x *GameStateSync) GetActionLog() [][]byte   { return x.ActionLog }

// ── Heartbeat ─────────────────────────────────────────────────────────────────

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum int64  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	Seq     int64  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Heartbeat) Reset()        {}
func (x *Heartbeat) String() string { return x.TableId }
func (x *Heartbeat) ProtoMessage() {}
func (x *Heartbeat) GetTableId() string { return x.TableId }
func (x *Heartbeat) GetHandNum() int64  { return x.HandNum }
func (x *Heartbeat) GetSeq() int64      { return x.Seq }

// ── TimeoutVote ───────────────────────────────────────────────────────────────

type TimeoutVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId           string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum           int64  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	VotingPlayerId    string `protobuf:"bytes,3,opt,name=voting_player_id,json=votingPlayerId,proto3" json:"voting_player_id,omitempty"`
	TimedoutPlayerId  string `protobuf:"bytes,4,opt,name=timedout_player_id,json=timedoutPlayerId,proto3" json:"timedout_player_id,omitempty"`
}

func (x *TimeoutVote) Reset()        {}
func (x *TimeoutVote) String() string { return x.VotingPlayerId }
func (x *TimeoutVote) ProtoMessage() {}
func (x *TimeoutVote) GetTableId() string          { return x.TableId }
func (x *TimeoutVote) GetHandNum() int64            { return x.HandNum }
func (x *TimeoutVote) GetVotingPlayerId() string    { return x.VotingPlayerId }
func (x *TimeoutVote) GetTimedoutPlayerId() string  { return x.TimedoutPlayerId }

// ── PotResult ─────────────────────────────────────────────────────────────────

type PotResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	WinnerIds []string `protobuf:"bytes,2,rep,name=winner_ids,json=winnerIds,proto3" json:"winner_ids,omitempty"`
}

func (x *PotResult) Reset()        {}
func (x *PotResult) String() string { return "pot" }
func (x *PotResult) ProtoMessage() {}
func (x *PotResult) GetAmount() int64      { return x.Amount }
func (x *PotResult) GetWinnerIds() []string { return x.WinnerIds }

// ── HandResult ────────────────────────────────────────────────────────────────

type HandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId   string       `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum   int64        `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	Pots      []*PotResult `protobuf:"bytes,3,rep,name=pots,proto3" json:"pots,omitempty"`
	StateRoot []byte       `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
}

func (x *HandResult) Reset()        {}
func (x *HandResult) String() string { return x.TableId }
func (x *HandResult) ProtoMessage() {}
func (x *HandResult) GetTableId() string    { return x.TableId }
func (x *HandResult) GetHandNum() int64     { return x.HandNum }
func (x *HandResult) GetPots() []*PotResult { return x.Pots }
func (x *HandResult) GetStateRoot() []byte  { return x.StateRoot }
